//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpOnClick.DAL.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LookupTypList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupTypList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErpOnClick.DAL.Common.LookupTypList", typeof(LookupTypList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 070.
        /// </summary>
        public static string Academic_Rank_070 {
            get {
                return ResourceManager.GetString("Academic_Rank_070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015.
        /// </summary>
        public static string ActiveStatus_015 {
            get {
                return ResourceManager.GetString("ActiveStatus_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 030.
        /// </summary>
        public static string AdmissionDocumentType_030 {
            get {
                return ResourceManager.GetString("AdmissionDocumentType_030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 031.
        /// </summary>
        public static string AdmissionFormStatus_031 {
            get {
                return ResourceManager.GetString("AdmissionFormStatus_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 026.
        /// </summary>
        public static string ALLOWANCE_TYPE_026 {
            get {
                return ResourceManager.GetString("ALLOWANCE_TYPE_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006.
        /// </summary>
        public static string ApplicationSourceType_006 {
            get {
                return ResourceManager.GetString("ApplicationSourceType_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007.
        /// </summary>
        public static string ApplicationStatus_007 {
            get {
                return ResourceManager.GetString("ApplicationStatus_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 073.
        /// </summary>
        public static string Assessment_Assignment_073 {
            get {
                return ResourceManager.GetString("Assessment_Assignment_073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 036.
        /// </summary>
        public static string AssetType_036 {
            get {
                return ResourceManager.GetString("AssetType_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 041.
        /// </summary>
        public static string AttendanceTypeNavigation_041 {
            get {
                return ResourceManager.GetString("AttendanceTypeNavigation_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 035.
        /// </summary>
        public static string AverageMethod_035 {
            get {
                return ResourceManager.GetString("AverageMethod_035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 016.
        /// </summary>
        public static string Banks_016 {
            get {
                return ResourceManager.GetString("Banks_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 019.
        /// </summary>
        public static string BloodGroup_019 {
            get {
                return ResourceManager.GetString("BloodGroup_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 022.
        /// </summary>
        public static string Board_022 {
            get {
                return ResourceManager.GetString("Board_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020.
        /// </summary>
        public static string CalculateIn_020 {
            get {
                return ResourceManager.GetString("CalculateIn_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005.
        /// </summary>
        public static string City_005 {
            get {
                return ResourceManager.GetString("City_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 068.
        /// </summary>
        public static string College_Type_068 {
            get {
                return ResourceManager.GetString("College_Type_068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 027.
        /// </summary>
        public static string CONTRACT_STATUS_027 {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 069.
        /// </summary>
        public static string Contract_Type_069 {
            get {
                return ResourceManager.GetString("Contract_Type_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004.
        /// </summary>
        public static string Country_004 {
            get {
                return ResourceManager.GetString("Country_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 040.
        /// </summary>
        public static string CourseEnrollStatus_040 {
            get {
                return ResourceManager.GetString("CourseEnrollStatus_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 024.
        /// </summary>
        public static string CourseType_024 {
            get {
                return ResourceManager.GetString("CourseType_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 050.
        /// </summary>
        public static string CurrentQualification_050 {
            get {
                return ResourceManager.GetString("CurrentQualification_050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string Degree_008 {
            get {
                return ResourceManager.GetString("Degree_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 066.
        /// </summary>
        public static string DegreeType_066 {
            get {
                return ResourceManager.GetString("DegreeType_066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        public static string Departments_001 {
            get {
                return ResourceManager.GetString("Departments_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 034.
        /// </summary>
        public static string DepreciationMethod_034 {
            get {
                return ResourceManager.GetString("DepreciationMethod_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010.
        /// </summary>
        public static string DocumentTypes_010 {
            get {
                return ResourceManager.GetString("DocumentTypes_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 057.
        /// </summary>
        public static string ExamType_057 {
            get {
                return ResourceManager.GetString("ExamType_057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 053.
        /// </summary>
        public static string Exception_Type_053 {
            get {
                return ResourceManager.GetString("Exception_Type_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 071.
        /// </summary>
        public static string Functional_Status_071 {
            get {
                return ResourceManager.GetString("Functional_Status_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 072.
        /// </summary>
        public static string Functional_Types_072 {
            get {
                return ResourceManager.GetString("Functional_Types_072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014.
        /// </summary>
        public static string Gende_014 {
            get {
                return ResourceManager.GetString("Gende_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 074.
        /// </summary>
        public static string GPA_Type_074 {
            get {
                return ResourceManager.GetString("GPA_Type_074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 051.
        /// </summary>
        public static string GradeStatus_051 {
            get {
                return ResourceManager.GetString("GradeStatus_051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 029.
        /// </summary>
        public static string HousingPaymentType_029 {
            get {
                return ResourceManager.GetString("HousingPaymentType_029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 056.
        /// </summary>
        public static string ID_Type_056 {
            get {
                return ResourceManager.GetString("ID_Type_056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 021.
        /// </summary>
        public static string Languages_021 {
            get {
                return ResourceManager.GetString("Languages_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 032.
        /// </summary>
        public static string LeaveType_032 {
            get {
                return ResourceManager.GetString("LeaveType_032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 037.
        /// </summary>
        public static string Loan_Status_37 {
            get {
                return ResourceManager.GetString("Loan_Status_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 033.
        /// </summary>
        public static string Loan_Type_033 {
            get {
                return ResourceManager.GetString("Loan_Type_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011.
        /// </summary>
        public static string MaritalStatus_011 {
            get {
                return ResourceManager.GetString("MaritalStatus_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 055.
        /// </summary>
        public static string MaterialType_055 {
            get {
                return ResourceManager.GetString("MaterialType_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 018.
        /// </summary>
        public static string MedicalClass_018 {
            get {
                return ResourceManager.GetString("MedicalClass_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 017.
        /// </summary>
        public static string MedicalCompany_017 {
            get {
                return ResourceManager.GetString("MedicalCompany_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012.
        /// </summary>
        public static string Nationality_012 {
            get {
                return ResourceManager.GetString("Nationality_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009.
        /// </summary>
        public static string OwnerType_009 {
            get {
                return ResourceManager.GetString("OwnerType_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 049.
        /// </summary>
        public static string PAYMENT_MODE_049 {
            get {
                return ResourceManager.GetString("PAYMENT_MODE_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 052.
        /// </summary>
        public static string Pending_Grade_Type_052 {
            get {
                return ResourceManager.GetString("Pending_Grade_Type_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 025.
        /// </summary>
        public static string POSITION_TYPE_025 {
            get {
                return ResourceManager.GetString("POSITION_TYPE_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 044.
        /// </summary>
        public static string ProjectStatus_044 {
            get {
                return ResourceManager.GetString("ProjectStatus_044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 043.
        /// </summary>
        public static string ProjectType_043 {
            get {
                return ResourceManager.GetString("ProjectType_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002.
        /// </summary>
        public static string RecruitmentJobStatus_002 {
            get {
                return ResourceManager.GetString("RecruitmentJobStatus_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003.
        /// </summary>
        public static string RecruitmentJobTypes_003 {
            get {
                return ResourceManager.GetString("RecruitmentJobTypes_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 039.
        /// </summary>
        public static string Relationship_039 {
            get {
                return ResourceManager.GetString("Relationship_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 013.
        /// </summary>
        public static string Religion_013 {
            get {
                return ResourceManager.GetString("Religion_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 042.
        /// </summary>
        public static string RequestType_042 {
            get {
                return ResourceManager.GetString("RequestType_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 023.
        /// </summary>
        public static string RoomsType_023 {
            get {
                return ResourceManager.GetString("RoomsType_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 067.
        /// </summary>
        public static string Special_Needs_067 {
            get {
                return ResourceManager.GetString("Special_Needs_067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 028.
        /// </summary>
        public static string State_028 {
            get {
                return ResourceManager.GetString("State_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 048.
        /// </summary>
        public static string STD_FEE_TYPE_048 {
            get {
                return ResourceManager.GetString("STD_FEE_TYPE_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 047.
        /// </summary>
        public static string Std_Letter_Type_047 {
            get {
                return ResourceManager.GetString("Std_Letter_Type_047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 046.
        /// </summary>
        public static string Student_Status_046 {
            get {
                return ResourceManager.GetString("Student_Status_046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 075.
        /// </summary>
        public static string Study_Type_075 {
            get {
                return ResourceManager.GetString("Study_Type_075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 054.
        /// </summary>
        public static string Submission_Assignment_054 {
            get {
                return ResourceManager.GetString("Submission_Assignment_054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 045.
        /// </summary>
        public static string TaskType_045 {
            get {
                return ResourceManager.GetString("TaskType_045", resourceCulture);
            }
        }
    }
}
